/*Problem Statement:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

//Every third fibonaaci number is an even number. Using the same looping can be reduced.

#include <stdio.h>

int main(void)
{
  int a=0;
  int b=1;
  int c=1;
  int t=0;  //Number of test cases
  int n=0;  //Number upto which sum is required

  while(t>n)
  {
    scanf("%d",&n)
    while(a<n)
    {
      a=b+c;
      b=a+c;
      c=a+b;
      sum+=a;
    }
    printf("%d",sum);
    sum=0; a=0; b=1; c=1;
  }
}
